default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: call-for-hack_<%= Rails.env %>

development:
  <<: *default
  username: postgres
  password: postgres

test:
  <<: *default
  username: postgres
  password: postgres

production:
  <<: *default
